# Generated by Django 4.2.1 on 2023-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/avatars/default.png', upload_to='static/images/posts'),
        ),
    ]
